import { Platform, StyleSheet } from "react-native";
import { useTheme } from "../context/darkModeContext";
import { dark, light } from "./colors";

const { theme } = useTheme;

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    padding: 10,
  },
  authContainer: {
    flex: 1,
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: light.primaryBg,
  },
  authCard: {
    backgroundColor: light.primaryCard,
    padding: 10,
    alignItems: "center",
    gap: 10,
    width: "90%",
    ...Platform.select({
      ios: {
        shadowColor: "black",
        shadowOffset: 5,
        shadowOpacity: 0.2,
        shadowRadius: 2,
      },
    }),
  },
  authHeader: {
    fontFamily: "interBold",
    fontSize: 22,
    marginBottom: 10,
    color: light.primaryIcon,
  },
  authInputwrapper: {
    flexDirection: "row",
    width: "100%",
    padding: 10,
    borderBottomColor: light.secondaryBg,
    borderBottomWidth: 2,
    borderTopRightRadius: 5,
    borderTopLeftRadius: 5,
    gap: 10,
    backgroundColor: "rgba(255, 121, 190, 0.1)",
  },
  authInput: {
    fontFamily: "interMedium",
    fontSize: 16,
    flex: 1,
  },
  authAction: {
    width: "100%",
    backgroundColor: light.secondaryBg,
    padding: 7,
    borderRadius: 5,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
  },
  loadingAuthAction: {
    width: "100%",
    borderColor: light.secondaryBg,
    borderWidth: 2,
    padding: 7,
    borderRadius: 5,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 5,
  },
  authActionText: {
    color: light.primaryIcon,
    fontFamily: "interSemiBold",
  },
  authQuery: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  authQuerytext: {
    fontFamily: "interMedium",
    fontSize: 12,
    color: light.primaryIcon,
  },
  toggler: {
    backgroundColor: light.secondaryBg,
    padding: 5,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 100,
  },
  togglerText: {
    fontFamily: "interBold",
    fontSize: 12,
    color: light.primaryIcon,
  },
  newCard: {
    flexDirection: "column",
    alignItems: "center",
    padding: 10,
    gap: 10,
    width: "90%",
    borderRadius: 5,
  },
  newHeader: {
    fontFamily: "interBold",
    fontSize: 20,
    marginBottom: 5,
  },
  title: {
    width: "100%",
    borderWidth: 1,
    padding: 7,
    borderRadius: 5,
    fontFamily: "interRegular",
    fontSize: 13,
  },
  des: {
    width: "100%",
    borderWidth: 1,
    padding: 5,
    borderRadius: 5,
    height: 45,
    fontFamily: "interRegular",
    fontSize: 12,
  },
  newDate: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    width: "100%",
    padding: 5,
    borderRadius: 3,
  },
  doneDate: {
    fontFamily: "interSemiBold",
    fontSize: 14,
  },
  addStepArea: {
    width: "100%",
    gap: 5,
    marginBottom: 10,
  },
  addStepHeader: {
    fontFamily: "interSemiBold",
    fontSize: 18,
  },
  addStepBtn: {
    flexDirection: "row",
    padding: 5,
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 3,
    marginBottom: 5,
  },
  addStepText: {
    fontFamily: "interSemiBold",
    fontSize: 14,
  },
  stepForm: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  step: {
    flex: 1,
    borderWidth: 1,
    padding: 5,
    borderRadius: 5,
    height: 45,
    fontFamily: "interRegular",
    fontSize: 10,
  },
  createBtn: {
    flexDirection: "row",
    width: "100%",
    padding: 5,
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 3,
    marginBottom: 5,
  },
});
